In [217]:
import pandas as pd
import numpy as np

In [218]:
df=pd.read_csv("heart_disease_uci.csv",index_col=0)

In [219]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
id,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [220]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [221]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 920 entries, 1 to 920
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    int64
 1   sex       920 non-null    object
 2   dataset   920 non-null    object
 3   cp        920 non-null    object
 4   trestbps  861 non-null    float64
 5   chol      890 non-null    float64
 6   fbs       830 non-null    object
 7   restecg   918 non-null    object
 8   thalch    865 non-null    float64
 9   exang     865 non-null    object
 10  oldpeak   858 non-null    float64
 11  slope     611 non-null    object
 12  ca        309 non-null    float64
 13  thal      434 non-null    object
 14  num       920 non-null    int64
dtypes: float64(5), int64(2), object(8)
memory usage: 115.0+ KB

In [222]:
df.isnull().sum()

age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [223]:
df.shape

(920, 15)

In [224]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
id,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [225]:
df['trestbps'].fillna(df['trestbps'].median(),inplace=True)
df['chol'].fillna(df['chol'].median(),inplace=True)
df['thalch'].fillna(df['thalch'].median(),inplace=True)
df['oldpeak'].fillna(df['oldpeak'].median(),inplace=True)

C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\1175168339.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['trestbps'].fillna(df['trestbps'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\1175168339.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['chol'].fillna(df['chol'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\1175168339.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['thalch'].fillna(df['thalch'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\1175168339.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['oldpeak'].fillna(df['oldpeak'].median(),inplace=True)

In [226]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
id,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [227]:
df.isnull().sum()

age           0
sex           0
dataset       0
cp            0
trestbps      0
chol          0
fbs          90
restecg       2
thalch        0
exang        55
oldpeak       0
slope       309
ca          611
thal        486
num           0
dtype: int64

In [228]:
from sklearn.preprocessing import OrdinalEncoder

In [229]:
oe=OrdinalEncoder()

In [230]:
df[['sex','dataset','cp','fbs','restecg','exang','slope','thal']]=oe.fit_transform(df[['sex','dataset','cp','fbs','restecg','exang','slope','thal']])

In [231]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
id,,,,,,,,,,,,,,,
1,63,1.0,0.0,3.0,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,0.0,0
2,67,1.0,0.0,0.0,160.0,286.0,0.0,0.0,108.0,1.0,1.5,1.0,3.0,1.0,2
3,67,1.0,0.0,0.0,120.0,229.0,0.0,0.0,129.0,1.0,2.6,1.0,2.0,2.0,1
4,37,1.0,0.0,2.0,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,1.0,0
5,41,0.0,0.0,1.0,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,1.0,0

In [232]:
df.isnull().sum()

age           0
sex           0
dataset       0
cp            0
trestbps      0
chol          0
fbs          90
restecg       2
thalch        0
exang        55
oldpeak       0
slope       309
ca          611
thal        486
num           0
dtype: int64

In [233]:
df['fbs'].fillna(df['fbs'].median(),inplace=True)
df['restecg'].fillna(df['restecg'].median(),inplace=True)
df['exang'].fillna(df['exang'].median(),inplace=True)
df['slope'].fillna(df['slope'].median(),inplace=True)
df['ca'].fillna(df['ca'].median(),inplace=True)
df.drop(columns=['thal'],inplace=True)

C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\3692532124.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fbs'].fillna(df['fbs'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\3692532124.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['restecg'].fillna(df['restecg'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\3692532124.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['exang'].fillna(df['exang'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\3692532124.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['slope'].fillna(df['slope'].median(),inplace=True)
C:\Users\vinot\AppData\Local\Temp\ipykernel_23340\3692532124.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ca'].fillna(df['ca'].median(),inplace=True)

In [234]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,num
id,,,,,,,,,,,,,,
1,63,1.0,0.0,3.0,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,0
2,67,1.0,0.0,0.0,160.0,286.0,0.0,0.0,108.0,1.0,1.5,1.0,3.0,2
3,67,1.0,0.0,0.0,120.0,229.0,0.0,0.0,129.0,1.0,2.6,1.0,2.0,1
4,37,1.0,0.0,2.0,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,0
5,41,0.0,0.0,1.0,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,0

In [235]:
df.isnull().sum()

age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
ca          0
num         0
dtype: int64

In [236]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [237]:
X=df.drop(columns=['num'])
y=df.num

In [238]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [239]:
nor=StandardScaler()
X_train=nor.fit_transform(X_train)
X_test=nor.transform(X_test)

In [240]:
model=RandomForestClassifier(criterion='entropy')
model.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy')

In [241]:
y_pred=model.predict(X_test)

In [242]:
y_pred

array([0, 0, 1, 4, 0, 0, 0, 3, 2, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0,
       3, 1, 3, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 1, 0, 2, 0,
       0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 3, 1, 0, 1, 1, 0, 0, 1, 3, 0, 1,
       0, 0, 1, 3, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 3, 2, 2,
       0, 3, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 0, 2, 0, 2, 0,
       0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 2, 0, 2, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 3, 1, 3, 1, 0, 1, 1, 1, 3, 0,
       0, 0, 0, 1, 1, 0, 1, 3, 0, 0, 0, 2, 0, 1, 0, 1, 3, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 3, 0, 0, 1])

In [245]:
print(f"{model.score(X_test,y_test)*100 :.1f}%")

57.1%